/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as DebtsIndexRouteImport } from './routes/debts/index'
import { Route as PeopleNewRouteImport } from './routes/people/new'
import { Route as PeoplePersonIdRouteImport } from './routes/people/$personId'
import { Route as DebtsNewRouteImport } from './routes/debts/new'
import { Route as DebtsDebtIdRouteImport } from './routes/debts/$debtId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsIndexRoute = DebtsIndexRouteImport.update({
  id: '/debts/',
  path: '/debts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleNewRoute = PeopleNewRouteImport.update({
  id: '/people/new',
  path: '/people/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsNewRoute = DebtsNewRouteImport.update({
  id: '/debts/new',
  path: '/debts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsDebtIdRoute = DebtsDebtIdRouteImport.update({
  id: '/debts/$debtId',
  path: '/debts/$debtId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/debts/$debtId': typeof DebtsDebtIdRoute
  '/debts/new': typeof DebtsNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/people/new': typeof PeopleNewRoute
  '/debts/': typeof DebtsIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/debts/$debtId': typeof DebtsDebtIdRoute
  '/debts/new': typeof DebtsNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/people/new': typeof PeopleNewRoute
  '/debts': typeof DebtsIndexRoute
  '/people': typeof PeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/debts/$debtId': typeof DebtsDebtIdRoute
  '/debts/new': typeof DebtsNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/people/new': typeof PeopleNewRoute
  '/debts/': typeof DebtsIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/debts/$debtId'
    | '/debts/new'
    | '/people/$personId'
    | '/people/new'
    | '/debts/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/debts/$debtId'
    | '/debts/new'
    | '/people/$personId'
    | '/people/new'
    | '/debts'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/debts/$debtId'
    | '/debts/new'
    | '/people/$personId'
    | '/people/new'
    | '/debts/'
    | '/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DebtsDebtIdRoute: typeof DebtsDebtIdRoute
  DebtsNewRoute: typeof DebtsNewRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PeopleNewRoute: typeof PeopleNewRoute
  DebtsIndexRoute: typeof DebtsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts/': {
      id: '/debts/'
      path: '/debts'
      fullPath: '/debts/'
      preLoaderRoute: typeof DebtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/new': {
      id: '/people/new'
      path: '/people/new'
      fullPath: '/people/new'
      preLoaderRoute: typeof PeopleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts/new': {
      id: '/debts/new'
      path: '/debts/new'
      fullPath: '/debts/new'
      preLoaderRoute: typeof DebtsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts/$debtId': {
      id: '/debts/$debtId'
      path: '/debts/$debtId'
      fullPath: '/debts/$debtId'
      preLoaderRoute: typeof DebtsDebtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DebtsDebtIdRoute: DebtsDebtIdRoute,
  DebtsNewRoute: DebtsNewRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PeopleNewRoute: PeopleNewRoute,
  DebtsIndexRoute: DebtsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
